DO $$
BEGIN
    CREATE TYPE TRACKER_TYPE AS ENUM ('global', 'player', 'beginner');
EXCEPTION
    WHEN duplicate_object THEN null;
END
$$;

DO $$
BEGIN
    CREATE TYPE EQUIP_TYPE AS ENUM ('pickaxe', 'lhand', 'rhand', 'manual', 'artifact');
EXCEPTION
    WHEN duplicate_object THEN null;
END
$$;

CREATE TABLE IF NOT EXISTS WORLDS (
    WORLD_ID TEXT PRIMARY KEY NOT NULL,
    WORLD_NAME TEXT NOT NULL UNIQUE,
    WORLD_DESC TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS TIERS (
    TIER_ID TEXT PRIMARY KEY NOT NULL,
    TIER_NAME TEXT NOT NULL UNIQUE,
    TIER_NUM INT NOT NULL UNIQUE,
    MIN_RARITY BIGINT NOT NULL,
    MAX_RARITY BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS ORES (
    ORE_ID TEXT PRIMARY KEY NOT NULL,
    ORE_NAME TEXT NOT NULL UNIQUE,
    TIER_ID TEXT REFERENCES TIERS(TIER_ID) NOT NULL
);

CREATE TABLE IF NOT EXISTS CAVES (
    CAVE_ID TEXT PRIMARY KEY NOT NULL,
    ORE_ID TEXT REFERENCES ORES(ORE_ID) NOT NULL,
    CAVE_NAME TEXT NOT NULL UNIQUE,
    WORLD_ID TEXT REFERENCES WORLDS(WORLD_ID) NOT NULL,
    CAVE_RARITY INT NOT NULL
);

CREATE TABLE IF NOT EXISTS LAYERS (
    LAYER_ID TEXT PRIMARY KEY NOT NULL,
    ORE_ID TEXT REFERENCES ORES(ORE_ID) NOT NULL,
    LAYER_NAME TEXT NOT NULL UNIQUE,
    WORLD_ID TEXT REFERENCES WORLDS(WORLD_ID) NOT NULL,
    MIN_DEPTH INT NOT NULL,
    MAX_DEPTH INT NOT NULL
);

CREATE TABLE IF NOT EXISTS SPAWNS (
    ORE_ID TEXT REFERENCES ORES(ORE_ID) NOT NULL,
    LAYER_ID TEXT REFERENCES LAYERS(LAYER_ID),
    CAVE_ID TEXT REFERENCES CAVES(CAVE_ID),
    RARITY BIGINT NOT NULL,
    CONSTRAINT ORE_SPAWN UNIQUE(ORE_ID, LAYER_ID, CAVE_ID)
);

CREATE TABLE IF NOT EXISTS GUILDS (
    GUILD_ID BIGINT PRIMARY KEY NOT NULL,
    GUILD_NAME TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS CHANNELS (
    CHANNEL_ID BIGINT PRIMARY KEY NOT NULL,
    CHANNEL_TYPE TRACKER_TYPE NOT NULL,
    PING_ROLE BIGINT
);

CREATE TABLE IF NOT EXISTS PLAYERS (
    USER_ID BIGINT PRIMARY KEY NOT NULL,
    PLAYER_NAME TEXT NOT NULL UNIQUE,
    GUILD_ID BIGINT REFERENCES GUILDS(GUILD_ID),
    MAX_EPI INT,
    MIN_EPI INT
);

CREATE TABLE IF NOT EXISTS TRACKERS (
    TRACKER_ID BIGINT PRIMARY KEY NOT NULL
);

CREATE TABLE IF NOT EXISTS EQUIPMENT (
    EQUIP_ID TEXT PRIMARY KEY NOT NULL,
    EQUIP_NAME TEXT NOT NULL,
    EQUIP_TIER INT NOT NULL CHECK (EQUIP_TIER <= 10 AND EQUIP_TIER >= 0),
    EQUIP_TYPE EQUIP_TYPE NOT NULL,
    WORLD_ID TEXT REFERENCES WORLDS(WORLD_ID) NOT NULL
);

CREATE TABLE IF NOT EXISTS RECIPES (
    EQUIP_ID TEXT REFERENCES EQUIPMENT(EQUIP_ID) NOT NULL,
    ORE_ID TEXT REFERENCES ORES(ORE_ID) NOT NULL,
    COUNT INT NOT NULL,
    CONSTRAINT RECIPE_STEP UNIQUE(EQUIP_ID, ORE_ID)
);

CREATE TABLE IF NOT EXISTS ABILITIES (
    ABILITY_ID TEXT PRIMARY KEY NOT NULL,
    EQUIP_ID TEXT REFERENCES EQUIPMENT(EQUIP_ID) NOT NULL,
    ABILITY_NAME TEXT NOT NULL,
    ABILITY_DESC TEXT NOT NULL,
    ABILITY_RATE INT NOT NULL,
    ABILITY_LUCK TEXT,
    ABILITY_LIFESPAN TEXT,
    ABILITY_AREA TEXT,
    ABILITY_AMOUNT TEXT
);

CREATE TABLE IF NOT EXISTS EVENTS (
    ORE_ID TEXT PRIMARY KEY REFERENCES ORES(ORE_ID) NOT NULL,
    WORLD_ID TEXT REFERENCES WORLDS(WORLD_ID) NOT NULL,
    EVENT_TEXT TEXT NOT NULL,
    EVENT_DESC TEXT NOT NULL,
    ORE_RARITY INT NOT NULL,
    EVENT_DURATION INT NOT NULL,
    EVENT_CHANCE INT NOT NULL
);

CREATE TABLE IF NOT EXISTS VARIANTS (
    VARIANT_ID TEXT PRIMARY KEY NOT NULL,
    VARIANT_NAME TEXT NOT NULL,
    VARIANT_NUM INT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS MULTIPLIERS (
    VARIANT_ID TEXT REFERENCES VARIANTS(VARIANT_ID) NOT NULL,
    TIER_ID TEXT REFERENCES TIERS(TIER_ID) NOT NULL,
    MULTIPLIER_NUM INT NOT NULL,
    CONSTRAINT MULTIPLIER UNIQUE(VARIANT_ID, TIER_ID)
);

CREATE TABLE IF NOT EXISTS TRACKS (
    PLAYER_NAME TEXT NOT NULL,
    ORE_ID TEXT REFERENCES ORES(ORE_ID) NOT NULL,
    VARIANT_ID TEXT REFERENCES VARIANTS(VARIANT_ID),
    CAVE_ID TEXT REFERENCES CAVES(CAVE_ID),
    WORLD_ID TEXT REFERENCES WORLDS(WORLD_ID) NOT NULL,
    BLOCKS_MINED BIGINT NOT NULL,
    EVENT_ID TEXT REFERENCES EVENTS(ORE_ID) NOT NULL,
    EQUIP_IDS TEXT[],
    CONSTRAINT TRACK_KEY UNIQUE(PLAYER_NAME, BLOCKS_MINED)
);